dist: trusty
sudo: false

addons:
  chrome: stable

branches:
  except:
  - domui-1.0

jdk:
- oraclejdk8

language: java

install: true
script: mvn -q clean install -Dmaven.test.skip=false

cache:
  directories:
  - $HOME/.m2

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/demo-deploy $DEPLOY_KEY
  on:
    branch: master

before_install:
- scripts/beforeInstall

after_failure:
  - echo $( pwd )
  - scripts/deploy-test-reports.sh
